language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  - stage: e2e
    - script: npm run test:e2e
  - stage: release
    - script: npm run release
    - branches:
      only:
        - master
  - stage:
    - script: git push origin master --tags
    - branches:
      only:
        - master
