language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: test
      script: "npm run test && npm run coveralls"
    - stage: e2e
      script: "npm run test:e2e"
