language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: e2e
      script: "npm run test:e2e"
    - stage: release
      script:
        - "npm run release"
        - "git push --follow-tags origin HEAD"
